plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable

Style/IfUnlessModifier:
  Exclude:
    - app/views/*/*.html.haml
